修掉HapSing元件umount產生的錯誤，因為原本有delay載入，umount時就揣無id
TypeError: document.getElementById(...) is null
[更多資訊]